### ISSUE TITLE
Musixmatch endpoint fail

### ISSUE THREAD

**Issue by Franr** [Franr/caulfield#2]
Sometimes it fail and the json() blows up:

```
[fran@frandora caulfield (master)]$ Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 587, in callit
    func(*args)
  File "/home/fran/code/caulfield/gui.py", line 38, in refresh_lyric
    self.data.process()
  File "/home/fran/code/caulfield/data_source.py", line 78, in process
    self.lyrics = self.lyric_source(current_artist, current_title).lyric
  File "/home/fran/code/caulfield/lyric_source.py", line 28, in lyric
    response = requests.get(self.ENDPOINT, payload).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by Franr** [comment]
Fixed here https://github.com/Franr/caulfield/commit/9b007c0faf17a81a101170bf5b8b71919abf3c0f#diff-e3f663554934f1e9a8bbc88149062abf
